/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws InterruptedException{
        Thread myThread = new Thread(() -> System.out.println(App.getGreeting()));
        myThread.start();
        Thread.yield();
        System.out.println("Hello from main thread");
        myThread.join();
    }
}
